# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: felipebrody10
# "service" is the name of this project. This will also be added to your AWS resource names.
service: fincheck-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128

package:
  individually: true

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  signUp:
    handler: src/main/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: get
