# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: felipebrody10
# "service" is the name of this project. This will also be added to your AWS resource names.
service: fincheck-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./sls/config/env.yml)}
  httpApi:
    disableDefaultEndpoint: ${env:DISABLE_DEFAULT_APIGW_ENDPOINT, false}
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience:
          - !Ref UserPoolClient

package:
  individually: true

custom:
  cognito:
    PoolName: ${self:service}-${self:provider.stage}-UserPool

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}
  - ${file(./sls/functions/accounts.yml)}
  - ${file(./sls/functions/transactions.yml)}
  - ${file(./sls/functions/recurringTransactions.yml)}
  - ${file(./sls/functions/creditCards.yml)}
  - ${file(./sls/functions/taxes.yml)}
  - ${file(./sls/functions/dashboard.yml)}
  - ${file(./sls/functions/users.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
  - ${file(./sls/resources/APIGWCustomDomain.yml)}
